### PR TITLE
Change csv url + add productID

### LINKED ISSUE #3: Landsat Pre-Collection depreciated -  Welcome Landsat Collection 1
per https://github.com/sat-utils/sat-api/issues/12 Landsat Pre-collection is depreciated since April 30. The `csv` https://github.com/sat-utils/landsat8-metadata/blob/6557d95c191addfa57eff41d396a371c54ab3a67/reader.py#L51 doesn't seems to be relevant anymore. 

We should switch to  https://landsat.usgs.gov/landsat/metadata_service/bulk_metadata_files/LANDSAT_8_C1.csv.gz

more info : https://landsat.usgs.gov/download-entire-collection-metadata

but as it's a `.gz` some work need to be done. Also maybe some refactoring need to be done on the database and the API.

cc @matthewhanson @drewbo @scisco

### PR DESCRIPTION
**Pull request by vincentsarago**
- [x] Change `csv` url to Collection 1 metadata csv
- [x] add productID

closes #3

ref: developmentseed/landsat-util#229

cc @matthewhanson @scisco @drewbo

### CODE REVIEW

**Comment by drewbo** [comment]
@vincentsarago will this result in duplication of records if we parse the whole csv? We should plan to make this a breaking change across a handful of products if we switch the `sceneID` parameter

**Comment by vincentsarago** [comment]
@drewbo you mean `is there multiple record (product_id) for each sceneID ?`. 

a quick check of the new csv:
```
$ cat LANDSAT_8_C1.csv | cut -d',' -f3 | sort | uniq | wc -l
  989789
$ cat LANDSAT_8_C1.csv | wc -l
  989789
```
There are `989789` different `sceneID` for `989789` lines in the csv, meaning no duplication. 

The `productID` is much more easy to parse than the `sceneID`, and gives more info. I think the switch might be good to do. 

first and last line of the new csv
```
browseAvailable,browseURL,sceneID,LANDSAT_PRODUCT_ID,sensor,acquisitionDate,dateUpdated,path,row,upperLeftCornerLatitude,upperLeftCornerLongitude,upperRightCornerLatitude,upperRightCornerLongitude,lowerLeftCornerLatitude,lowerLeftCornerLongitude,lowerRightCornerLatitude,lowerRightCornerLongitude,sceneCenterLatitude,sceneCenterLongitude,cloudCover,cloudCoverFull,dayOrNight,sunElevation,sunAzimuth,receivingStation,sceneStartTime,sceneStopTime,imageQuality1,DATA_TYPE_L1,cartURL,ROLL_ANGLE,GEOMETRIC_RMSE_MODEL,GEOMETRIC_RMSE_MODEL_X,GEOMETRIC_RMSE_MODEL_Y,FULL_PARTIAL_SCENE,NADIR_OFFNADIR,PROCESSING_SOFTWARE_VERSION,CPF_NAME,RLUT_FILE_NAME,BPF_NAME_OLI,BPF_NAME_TIRS,GROUND_CONTROL_POINTS_MODEL,GROUND_CONTROL_POINTS_VERSION,DATE_L1_GENERATED,TIRS_SSM_MODEL,COLLECTION_NUMBER,COLLECTION_CATEGORY,CLOUD_COVER_LAND
Y,http://earthexplorer.usgs.gov/browse/landsat_8/2017/179/009/LC08_L1GT_179009_20170515_20170515_01_RT.jpg,LC81790092017135LGN00,LC08_L1GT_179009_20170515_20170515_01_RT,OLI_TIRS,2017-05-15,2017-05-15,179,9,73.38306,50.9226,72.51896,56.02555,71.81994,48.32092,71.0155,53.11975,72.20676,52.1035,7,71.31,DAY,36.73103357,-179.41529079,LGN,2017:135:08:29:37.5759360,2017:135:08:30:09.3459330,9,L1GT,http://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LC81790092017135LGN00,-.001,0,0,0,FULL,NADIR,LPGS_2.7.0,LC08CPF_20170401_20170630_01.02,LC08RLUT_20150303_20431231_01_12.h5,LO8BPF20170515081519_20170515085842.01,LT8BPF20170511075931_20170511102015.01,-1,4,2017-05-15 07:44:46,PRELIMINARY,1,RT,74.16
...
...
Y,http://earthexplorer.usgs.gov/browse/landsat_8/2013/126/061/LT08_L1GT_126061_20130308_20170505_01_T2_TIR.jpg,LT81260612013067LGN02,LT08_L1GT_126061_20130308_20170505_01_T2,TIRS,2013-03-08,2017-05-05,126,61,-.41901,100.97018,-.75575,102.54168,-2.139,100.60417,-2.47323,102.17747,-1.44722,101.5731,0,-1,DAY,60.09467258,97.228178,LGN,2013:067:03:25:09.3125530,2013:067:03:25:46.2117040,9,L1GT,http://earthexplorer.usgs.gov/order/process?dataset_name=LANDSAT_8_C1&ordered=LT81260612013067LGN02,0,0,0,0,FULL,NADIR,LPGS_2.7.0,LC08CPF_20130101_20130331_01.01,LC08RLUT_20130211_20150302_01_11.h5,N/A,LT8BPF20130308032013_20130308032801.01,-1,-1,2017-05-05 11:21:03,ACTUAL,1,T2,-1
```

**Comment by drewbo** [comment]
Looks like product id isn't completely unique though (`989764` uniques) and would break some downstream consumers as well. Let's check with @scisco too and then good to merge

**Comment by vincentsarago** [comment]
`LANDSAT_PRODUCT_ID` with multiple sceneID: 
```
LC08_L1GT_205003_20130326_20170505_01_T2
LC08_L1GT_205004_20130326_20170505_01_T2
LC08_L1GT_205005_20130326_20170505_01_T2
LC08_L1GT_205006_20130326_20170505_01_T2
LC08_L1GT_205247_20130326_20170505_01_T2
LC08_L1GT_205248_20130326_20170505_01_T2
LC08_L1GT_214012_20130325_20170505_01_T2
LC08_L1GT_214013_20130325_20170505_01_T2
LC08_L1GT_221012_20130326_20170505_01_T2
LC08_L1GT_221016_20130326_20170505_01_T2
LC08_L1GT_221017_20130326_20170505_01_T2
LC08_L1GT_221246_20130326_20170505_01_T2
LC08_L1TP_189247_20130326_20170505_01_T1
LC08_L1TP_189248_20130326_20170505_01_T2
LC08_L1TP_205001_20130326_20170505_01_T2
LC08_L1TP_214014_20130325_20170505_01_T1
LC08_L1TP_214015_20130325_20170505_01_T2
LC08_L1TP_221001_20130326_20170505_01_T1
LC08_L1TP_221002_20130326_20170505_01_T2
LC08_L1TP_221003_20130326_20170505_01_T1
LC08_L1TP_221013_20130326_20170505_01_T2
LC08_L1TP_221014_20130326_20170505_01_T1
LC08_L1TP_221015_20130326_20170505_01_T1
```

sceneID for `LC08_L1GT_214012_20130325_20170505_01_T2`:
`LC82140122013084LGN02` && `LC82140122013084NSG02`

product difference: `LGN` && `NSG`

To me it seems this only happened for some of the first scenes. you could filter manually the `NSG` records


cc @drewbo @scisco

**Pull request merged**
